In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
diccionario = pd.read_csv('..\\data\\data_dictionary.csv')

clinical = pd.read_csv('..\\data\\hantavirus_clinical.csv')
country_y = pd.read_csv('..\\data\\hantavirus_country_yearly.csv')
environm = pd.read_csv('..\\data\\hantavirus_environmental.csv')
master = pd.read_csv('..\\data\\hantavirus_master.csv')
month_trends = pd.read_csv('..\\data\\hantavirus_monthly_trends.csv')
outbreaks = pd.read_csv('..\\data\\hantavirus_outbreaks.csv')
strains = pd.read_csv('..\\data\\hantavirus_virus_strains.csv')

datasets = [clinical, country_y, environm, master, month_trends, outbreaks, strains]

In [3]:
j=0
for i in datasets[j].columns:
    print(i)

patient_id
year
country
syndrome
age
sex
symptoms
incubation_days
severity
hospitalized
icu_admission
mechanical_ventilation
ecmo_used
dialysis
comorbidity
exposure_type
outcome
length_of_stay_days

In [20]:
j = 0
print(datasets[j].info())
datasets[j].sample(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   patient_id              8000 non-null   object
 1   year                    8000 non-null   int64
 2   country                 8000 non-null   object
 3   syndrome                8000 non-null   object
 4   age                     8000 non-null   int64
 5   sex                     8000 non-null   object
 6   symptoms                8000 non-null   object
 7   incubation_days         8000 non-null   int64
 8   severity                8000 non-null   object
 9   hospitalized            8000 non-null   int64
 10  icu_admission           8000 non-null   int64
 11  mechanical_ventilation  8000 non-null   int64
 12  ecmo_used               8000 non-null   int64
 13  dialysis                8000 non-null   int64
 14  comorbidity             4801 non-null   object
 15  exposure_type           8000 non-null   object
 16  outcome                 8000 non-null   object
 17  length_of_stay_days     8000 non-null   int64
dtypes: int64(9), object(9)
memory usage: 1.1+ MB
None

,patient_id,year,country,syndrome,age,sex,symptoms,incubation_days,severity,hospitalized,icu_admission,mechanical_ventilation,ecmo_used,dialysis,comorbidity,exposure_type,outcome,length_of_stay_days
7667,PT-07668,2004,Finland,HFRS,38,Male,"Fever, Blurred Vision, Conjunctival Injection",10,Mild,0,0,0,0,0,NaN,Camping/hiking,Recovered,0
197,PT-00198,2001,Russia,HFRS,36,Female,"Myalgia, Facial Flushing, Conjunctival Injecti...",23,Moderate,1,0,0,0,0,Chronic Kidney Disease,Close contact with HPS patient,Recovered,6
7436,PT-07437,2022,Russia,HFRS,48,Male,"Blurred Vision, Myalgia, Abdominal Pain, Fever",20,Mild,1,0,0,0,0,Cardiovascular Disease,Cleaning rodent-infested area,Recovered,19
7936,PT-07937,2011,Bolivia,HPS,33,Male,"Dizziness, Fatigue, Vomiting, Hypotension, Tac...",8,Moderate,1,0,0,0,0,Obesity,Unknown,Recovered,6
6759,PT-06760,2005,Slovenia,HFRS,29,Male,"Proteinuria, Hypotension, Nausea",24,Moderate,1,0,0,0,0,NaN,Close contact with HPS patient,Recovered,4

In [8]:
diccionario

,file,column,dtype,description
0,hantavirus_country_yearly.csv,year,int,Calendar year (1993-2026)
1,hantavirus_country_yearly.csv,iso3,str,ISO 3166-1 alpha-3 country code
2,hantavirus_country_yearly.csv,country,str,Country name
3,hantavirus_country_yearly.csv,who_region,str,WHO regional office (AMRO/EURO/WPRO)
4,hantavirus_country_yearly.csv,syndrome,str,Disease syndrome: HPS or HFRS
5,hantavirus_country_yearly.csv,confirmed_cases,int,Annual confirmed hantavirus cases
6,hantavirus_country_yearly.csv,deaths,int,Annual deaths from hantavirus
7,hantavirus_country_yearly.csv,case_fatality_rate,float,Case fatality rate (deaths/cases)
8,hantavirus_country_yearly.csv,hospitalized,int,Number of hospitalized patients
9,hantavirus_country_yearly.csv,icu_admissions,int,ICU admissions count
10,hantavirus_country_yearly.csv,human_to_human_cases,int,Documented human-to-human transmission cases
11,hantavirus_clinical.csv,patient_id,str,Unique synthetic patient identifier
12,hantavirus_clinical.csv,severity,str,Clinical severity: Mild/Moderate/Severe/Critical
13,hantavirus_clinical.csv,outcome,str,Patient outcome: Recovered/Deceased
14,hantavirus_clinical.csv,ecmo_used,int,Whether ECMO was used (0/1)
15,hantavirus_clinical.csv,exposure_type,str,Type of rodent/environmental exposure
16,hantavirus_environmental.csv,rodent_abundance_index,float,Normalized rodent population index (0-1)
17,hantavirus_environmental.csv,ndvi,float,Normalized Difference Vegetation Index (0-1)
18,hantavirus_environmental.csv,deforestation_rate_pct,float,Annual deforestation rate percentage
19,hantavirus_outbreaks.csv,trigger,str,Environmental or social trigger for outbreak
20,hantavirus_virus_strains.csv,h2h_transmission,str,Whether human-to-human transmission is documented
21,hantavirus_virus_strains.csv,reservoir_host,str,Primary rodent reservoir host species

Para este análisis de los casos y distribución del Hantavirus, se utilizarán variables de la tabla ```clinical```
### Variable dependiente
```y: length of stay days``` (int)
### Variables independientes
```x_1: country``` - cualitativa, nombre del país \
```x_2: syndrome``` - cualitativa binaria (HPS o HFRS) \
```x_3: age``` - cuantitativa discreta (int) \
```x_4: sex``` - cualitativa binaria (Male, Female) \
```x_5: severity``` - cualitativa, 4 valores: Mild/Moderate/Severe/Critical \
```x_6: outcome``` - cualitativa binaria (Recovered/Deceased)

### Para la regresión lineal:
Las variables cualitativas, exceptuando el país, serán traducidas a enteros en orden creciente:
- Las variables binarias serán transformadas a variables 0/1
- La variable ```severity``` constará con cuatro valores: 0, 1, 2 y 3; estos corresponden, en orden, a los valores Mild, Moderate, Severe y Critical